# Microservices_Jaeger
# Asset Service Lambda Function

# Overview

The Asset Service Lambda Function is a .NET-based AWS Lambda function that retrieves and displays asset information using the Alpaca API while incorporating distributed tracing with OpenTelemetry and exporting traces to a Jaeger instance. It is designed to provide information about assets available on the Alpaca platform. This README provides an overview of the code and its functionality.

# Prerequisites

Before deploying and using this Lambda function, make sure you have the following:

1. **AWS Lambda**:
   Set up an AWS Lambda environment with the necessary permissions and an API Gateway trigger to receive requests.

2. **Alpaca API Keys**:
    You need to have valid Alpaca API keys, including the API key ID and secret key, for authentication with the Alpaca API.

3. **Jaeger Setup**:
   You should have a Jaeger instance configured and running to receive and visualize the traces generated by the Lambda function.

# Code Structure

## Function
   This class contains the Lambda function's main logic, including the handling of API Gateway events, asset retrieval, and tracing.

## Static Constructor
  The static constructor initializes the tracing configuration using OpenTelemetry and sets up the Jaeger exporter. It also configures the Alpaca API client using your API key and secret key.

## FunctionHandler
  This method is the entry point for the Lambda function. It receives an API Gateway request and retrieves asset information from the Alpaca API. The retrieved assets are transformed into a JSON response.

## AssetDetails
  This class represents the structure of asset details, including symbol, name, exchange, tradable status, and asset status.

## MapAssetStatusToString
  A helper method to map asset status from Alpaca's format to a more human-readable format.
  
# Features

  ## Asset Retrieval
   The function communicates with the Alpaca API to retrieve a list of active assets.

  ## Distributed Tracing
   OpenTelemetry is integrated for distributed tracing. The function creates and logs spans to capture various aspects of its execution.

  ## Latency Injection
   The function simulates a delay between 20 and 70 seconds to mimic real-world scenarios, and this delay is captured in the trace.


## Functionality

The Asset Service Lambda Function operates as follows:

1. It receives an incoming request via API Gateway, typically containing no specific parameters.

2. The function uses OpenTelemetry to create a tracing span called "AssetExecution" to track its execution.

3. It communicates with the Alpaca API to retrieve a list of active assets. These assets include information such as symbol, name, exchange, tradability, and status.

4. The retrieved asset details are mapped and stored in a list.

5. The function serializes the list of assets into JSON and adds the total count of assets as an attribute to the tracing span.

6. To mimic real-world conditions, the function introduces a time delay between 20 and 70 seconds (simulated latency). The delay is included as an attribute in the tracing span.

7. The function returns an API Gateway response with a status code of 200 and the asset details in JSON format.

8. In case of an exception, the function captures error information in a tracing span and returns a response with a 500 status code and an error message.

## Configuration

Before deploying this Lambda function, make sure to configure the following:

- **Alpaca API Keys**
   Replace the placeholders for the Alpaca API key and secret key in the code with your actual API credentials.

- **Jaeger Exporter**
   Update the Jaeger agent host and port in the static constructor to match your Jaeger setup.

- **AWS Lambda**
   Configure the Lambda function with an appropriate role, triggers, and memory settings. Ensure that the function has the necessary permissions to interact with the Alpaca API and export traces to Jaeger.

## Deployment

You can deploy this Lambda function to your AWS environment using the AWS Management Console, AWS CLI, or AWS CloudFormation. Ensure that the necessary dependencies and AWS SDKs are installed on your development environment.

## Monitoring

- **Jaeger**: Monitor the traces generated by the Lambda function in your Jaeger instance to gain insights into the execution and performance.

## Conclusion

The Asset Service Lambda Function serves as a demonstration of a serverless function that interacts with an external API, captures distributed tracing information, and introduces variable response times. It can be a foundation for building more complex serverless applications with similar requirements, such as capturing and exporting traces for monitoring and troubleshooting purposes.
